import { prisma } from "./db.js";
import { config } from "./config.js";
export type Hit = { id:string; documentId:string; documentName:string; text:string; pageNumber:number; chunkIndex:number; score:number };
const tokenize = (value:string): string[] => value.toLocaleLowerCase("zh-CN").match(/[\u4e00-\u9fff]|[a-z0-9]+/g) || [];
function bm25(query:string, texts:string[]) { const terms = [...new Set(tokenize(query))]; const tokenized = texts.map(tokenize); const avg = tokenized.reduce((sum, value) => sum + value.length, 0) / Math.max(1, tokenized.length); return tokenized.map((tokens) => terms.reduce((score, term) => { const count = tokens.filter((x) => x === term).length; if (!count) return score; const docs = tokenized.filter((x) => x.includes(term)).length; const idf = Math.log(1 + (texts.length - docs + 0.5) / (docs + 0.5)); return score + idf * ((count * 2.2) / (count + 1.2 * (1 - 0.75 + 0.75 * tokens.length / Math.max(1, avg)))); }, 0)); }
function coverage(query:string, text:string) { const terms = tokenize(query); const body = text.toLocaleLowerCase("zh-CN"); const weight = (term:string) => /\d|[省市县区乡镇]|补贴|条例|办法|通知|政策/.test(term) ? 2 : 1; const total = terms.reduce((sum, term) => sum + weight(term), 0) || 1; return terms.reduce((sum, term) => sum + (body.includes(term) ? weight(term) : 0), 0) / total; }
async function embedding(input:string) { if (!config.embeddingsBaseUrl || !config.embeddingsModel) throw new Error("检索服务尚未配置，请联系管理员"); const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), config.embeddingsTimeoutMs); try { const response = await fetch(config.embeddingsBaseUrl.replace(/\/$/, "") + "/embeddings", { method:"POST", signal: controller.signal, headers:{"content-type":"application/json", ...(config.embeddingsApiKey ? {authorization:"Bearer " + config.embeddingsApiKey} : {})}, body:JSON.stringify({model:config.embeddingsModel,input}) }); if (!response.ok) throw new Error("检索服务暂时不可用，请稍后重试"); const body = await response.json() as {data?:Array<{embedding?:number[]}>}; const vector = body.data?.[0]?.embedding; if (!vector?.length || vector.some((x) => !Number.isFinite(x))) throw new Error("检索服务未返回有效结果"); return vector; } finally { clearTimeout(timeout); } }
function parseVector(raw:string|null) { if (!raw) return null; const vector = raw.replace(/^\[|\]$/g, "").split(",").map(Number); return vector.length && vector.every(Number.isFinite) ? vector : null; }
function cosine(a:number[], b:number[]) { if (a.length !== b.length || !a.length) return 0; let dot=0, aa=0, bb=0; for (let i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]**2;bb+=b[i]**2;} return aa&&bb ? dot/Math.sqrt(aa*bb) : 0; }
export async function retrieve(categoryId:string, query:string, documentIds:string[] = []) {
  const documents = await prisma.document.findMany({ where:{categoryId,deletedAt:null,mimeType:"application/pdf",indexStatus:"ready",...(documentIds.length ? {id:{in:documentIds}} : {})}, include:{versions:true} });
  const active = documents.flatMap((document) => { const version = document.versions.find((candidate) => candidate.version === document.version && candidate.indexStatus === "ready"); return version ? [{document,version}] : []; }); if (!active.length) return [];
  const chunks = await prisma.documentChunk.findMany({ where:{categoryId,documentId:{in:active.map((x)=>x.document.id)},documentVersionId:{in:active.map((x)=>x.version.id)}} }); if (!chunks.length) return [];
  const keywordScores = bm25(query, chunks.map((x)=>x.text)); let queryVector: number[] | null = null; try { queryVector = await embedding(query); } catch (error) { console.warn("semantic retrieval unavailable; using keyword retrieval", error); }
  const rows = queryVector ? await prisma.$queryRawUnsafe<Array<{id:string;embedding:string|null}>>('SELECT id, embedding::text AS embedding FROM "DocumentChunk" WHERE id = ANY($1::text[])', chunks.map((x)=>x.id)) : []; const vectors = new Map(rows.map((row)=>[row.id,parseVector(row.embedding)]));
  const ranked = chunks.map((chunk,index)=>({chunk,keyword:keywordScores[index],semantic:queryVector ? cosine(queryVector,vectors.get(chunk.id)||[]) : 0})); const keywordTop=[...ranked].sort((a,b)=>b.keyword-a.keyword).slice(0,20); const semanticTop=queryVector ? [...ranked].filter((row) => vectors.get(row.chunk.id)?.length).sort((a,b)=>b.semantic-a.semantic).slice(0,20) : []; const fused=new Map<string,{row:(typeof ranked)[number];rrf:number}>(); const add=(row:(typeof ranked)[number],rank:number)=>{const current=fused.get(row.chunk.id)||{row,rrf:0};current.rrf+=1/(60+rank+1);fused.set(row.chunk.id,current)}; keywordTop.forEach(add); semanticTop.forEach(add);
  const candidates=[...fused.values()].sort((a,b)=>b.rrf-a.rrf).slice(0,10); const max=Math.max(...candidates.map((x)=>x.rrf),1); const names=new Map(active.map((x)=>[x.document.id,x.document.fileName])); return candidates.map(({row,rrf})=>({id:row.chunk.id,documentId:row.chunk.documentId,documentName:names.get(row.chunk.documentId)||"政策文件",text:row.chunk.text,pageNumber:row.chunk.pageNumber,chunkIndex:row.chunk.chunkIndex,score:.7*(rrf/max)+.3*coverage(query,row.chunk.text)})).sort((a,b)=>b.score-a.score).filter((hit,index,all)=>all.findIndex((candidate)=>candidate.documentId===hit.documentId&&Math.abs(candidate.chunkIndex-hit.chunkIndex)<=1)===index).slice(0,3);
}
